name: embedding_sequencer_env
channels:
- conda-forge
dependencies:
- biopython=1.84
- bzip2=1.0.8
- c-ares=1.34.3
- ca-certificates=2024.8.30
- cached-property=1.5.2
- cached_property=1.5.2
- cpython=3.12.8
- faiss=1.8.0
- faiss-cpu=1.8.0
- filelock=3.16.1
- fsspec=2024.10.0
- gmp=6.3.0
- gmpy2=2.1.5
- h5py=3.12.1
- hdf5=1.14.3
- jinja2=3.1.4
- joblib=1.4.2
- krb5=1.21.3
- libabseil=20240722.0
- libaec=1.1.3
- libblas=3.9.0
- libcblas=3.9.0
- libcurl=8.10.1
- libcxx=19.1.5
- libedit=3.1.20191231
- libev=4.33
- libexpat=2.6.4
- libfaiss=1.8.0
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=13.2.0
- liblapack=3.9.0
- liblzma=5.6.3
- libnghttp2=1.64.0
- libopenblas=0.3.28
- libprotobuf=5.28.2
- libsqlite=3.47.0
- libssh2=1.11.1
- libtorch=2.5.1
- libuv=1.49.2
- libzlib=1.3.1
- llvm-openmp=19.1.5
- markupsafe=3.0.2
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- ncurses=6.5
- networkx=3.4.2
- nomkl=1.0
- numpy=1.26.4
- openssl=3.4.0
- packaging=24.2
- pip=24.3.1
- python=3.12.8
- python_abi=3.12
- pytorch=2.5.1
- readline=8.2
- scikit-learn=1.5.2
- scipy=1.14.1
- setuptools=75.6.0
- sleef=3.7
- sympy=1.13.3
- tk=8.6.13
- threadpoolctl=3.5.0
- typing_extensions=4.12.2
- tzdata=2024b
- wheel=0.45.1
- zstd=1.5.6

